spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/athletehub
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: 522dee5738f6cea7fd3ff41a00928212a4bec1a0987c5621be2d88e47796f403f9c507cb605ab2f2aaa358b686cb642f30f97f319716916ec0d53b95b39aa8c6

  jpa:
    mapping-resources: orm.xml
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
